package com.simprints.id.exceptions.safe.secure


class AuthException(cause: Throwable) : RuntimeException(cause)
